### PR TITLE
Add parameter for ManagedRepository system group

### PR DESCRIPTION
**Pull request by manics**
If the directory doesn't already exist, or if `omero_datadir_chown: True`, does a `chgrp` and `chmod` so `ManagedRepository` is group writeable.

New functionality, should be non-breaking, tag 1.2.0?

### CODE REVIEW

**Comment by joshmoore** [comment]
* re: "1.2.0" - WFM as an addition
 * re: the changes look to make sense and the current test is green, but this might be one where it's best to have production (integration) testing.

**Comment by manics** [comment]
@openmicroscopy/devops any volunteers to test this?

**Comment by manics** [comment]
I've added a test for inplace import, and set the default umask to `0002`.

**Comment by manics** [comment]
I've fixed the vagrant test, there was an error that was hidden by a [bug in testinfra](https://github.com/philpep/testinfra/pull/180).

**Comment by joshmoore** [comment]
Even with testinfra 1.5.3 , I'm not getting this to pass:

```
ry\n================================================================================\nInstall  9 Packages (+70 Dependent packages)\n\nTotal download size: 75 M\nInstalled size: 232 M\nDownloading packages:\n--------------------------------------------------------------------------------\nTotal                                              513 kB/s |  75 MB  02:29     \nRunning transaction check\nRunning transaction test\n"]}

PLAY RECAP *********************************************************************
omero-server-ice35         : ok=4    changed=3    unreachable=0    failed=1
omero-server-ice36         : ok=4    changed=3    unreachable=0    failed=1
```

**Comment by manics** [comment]
You shouldn't need testinfra 1.5.3, that was just a bug which obscured the problem. What's the actual error you're seeing?

**Comment by joshmoore** [comment]
The output is cleaner (and different) on vagrant than on docker:

```
TASK [ansible-role-omero-server : omero | install omero] ***********************
fatal: [omero-server-ice36]: FAILED! => {"changed": false, "cmd": "/home/omero/omego/bin/omego install --release latest --sym OMERO.server --prestartfile /home/omero/config/omero-base.config --prestartfile /home/omero/config/omero-additional.config --ice 3.6 -qq --no-start --dbhost localhost --dbuser omero --dbname omero --dbpass omero --rootpass omero --initdb", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [omero-server-ice35]: FAILED! => {"changed": false, "cmd": "/home/omero/omego/bin/omego install --release latest --sym OMERO.server --prestartfile /home/omero/config/omero-base.config --prestartfile /home/omero/config/omero-additional.config --ice 3.5 -qq --no-start --dbhost localhost --dbuser omero --dbname omero --dbpass omero --rootpass omero --initdb", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

RUNNING HANDLER [openmicroscopy.nginx : restart nginx] *************************

RUNNING HANDLER [openmicroscopy.postgresql : restart postgresql] ***************

PLAY RECAP *********************************************************************
omero-server-ice35         : ok=45   changed=35   unreachable=0    failed=1
omero-server-ice36         : ok=47   changed=37   unreachable=0    failed=1
```

**Comment by manics** [comment]
Ansible 2.2? that's not supported by this role yet.

**Comment by joshmoore** [comment]
Can you cherry-pick :

```
commit b2babd26115884c9d4ac593ae0aade402393ee70
Author: jmoore <josh@glencoesoftware.com>
Date:   Wed Feb 1 19:46:10 2017 +0100

    Add requirements file for ansible<2.2
```

**Comment by joshmoore** [comment]
Hmmm... still failing:

```
TASK [openmicroscopy.ice : zeroc ice | install devel packages] *****************
changed: [omero-server-ice35] => (item=[u'ice-c++-devel', u'ice-java-devel', u'ice-python-devel'])
failed: [omero-server-ice36] (item=[u'ice-all-devel']) => {"changed": true, "failed": true, "item": ["ice-all-devel"], "msg": "https://zeroc.com/download/rpm/el7/x86_64/libice-java-3.6.3-1.el7.x86_64.rpm: [Errno 14] curl#18 - \"transfer closed with 915304 bytes remaining to read\"\nTrying other mirror.\n\n\nError downloading packages:\n  libice-java-3.6.3-1.el7.x86_64: [Errno 256] No more mirrors to try.\n\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.datente.com\n * epel: mirror.serverbeheren.nl\n * extras: mirror.yannic-bonenberger.com\n * updates: centos.datente.com\nResolving Dependencies\n--> Running transaction check\n---> Package ice-all-devel.x86_64 0:3.6.3-1.el7 will be installed\n--> Processing Dependency: php-ice-devel(x86-64) = 3.6.3-1.el7 for package: ice-all-devel-3.6.3-1.el7.x86_64\n--> Processing Dependency: libice-java(x86-64) = 3.6.3-1.el7 for package: ice-all-devel-3.6.3-1.el7.x86_64\n--> Processing Dependency: libice-c++-devel(x86-64) = 3.6.3-1.el7 for package: ice-all-devel-3.6.3-1.el7.x86_64\n--> Running transaction check\n---> Package libice-c++-devel.x86_64 0:3.6.3-1.el7 will be installed\n--> Processing Dependency: ice-slice = 3.6.3-1.el7 for package: libice-c++-devel-3.6.3-1.el7.x86_64\n--> Processing Dependency: glibc-devel(x86-64) for package: libice-c++-devel-3.6.3-1.el7.x86_64\n---> Package libice-java.x86_64 0:3.6.3-1.el7 will be installed\n--> Processing Dependency: libdb-java(x86-64) >= 5.3.21 for package: libice-java-3.6.3-1.el7.x86_64\n---> Package php-ice-devel.x86_64 0:3.6.3-1.el7 will be installed\n--> Running transaction check\n---> Package glibc-devel.x86_64 0:2.17-157.el7_3.1 will be installed\n--> Processing Dependency: glibc-headers = 2.17-157.el7_3.1 for package: glibc-devel-2.17-157.el7_3.1.x86_64\n--> Processing Dependency: glibc = 2.17-157.el7_3.1 for package: glibc-devel-2.17-157.el7_3.1.x86_64\n--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-157.el7_3.1.x86_64\n---> Package ice-slice.noarch 0:3.6.3-1.el7 will be installed\n---> Package libdb-java.x86_64 0:5.3.21-19.el7 will be installed\n--> Running transaction check\n---> Package glibc.x86_64 0:2.17-106.el7_2.8 will be updated\n--> Processing Dependency: glibc = 2.17-106.el7_2.8 for package: glibc-common-2.17-106.el7_2.8.x86_64\n---> Package glibc.x86_64 0:2.17-157.el7_3.1 will be an update\n---> Package glibc-headers.x86_64 0:2.17-157.el7_3.1 will be installed\n--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-157.el7_3.1.x86_64\n--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-157.el7_3.1.x86_64\n--> Running transaction check\n---> Package glibc-common.x86_64 0:2.17-106.el7_2.8 will be updated\n---> Package glibc-common.x86_64 0:2.17-157.el7_3.1 will be an update\n---> Package kernel-headers.x86_64 0:3.10.0-514.6.1.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package            Arch     Version               Repository              Size\n================================================================================\nInstalling:\n ice-all-devel      x86_64   3.6.3-1.el7           zeroc-ice-el7           13 k\nInstalling for dependencies:\n glibc-devel        x86_64   2.17-157.el7_3.1      updates                1.1 M\n glibc-headers      x86_64   2.17-157.el7_3.1      updates                668 k\n ice-slice          noarch   3.6.3-1.el7           zeroc-ice-el7-noarch    72 k\n kernel-headers     x86_64   3.10.0-514.6.1.el7    updates                4.8 M\n libdb-java         x86_64   5.3.21-19.el7         base                   1.3 M\n libice-c++-devel   x86_64   3.6.3-1.el7           zeroc-ice-el7          426 k\n libice-java        x86_64   3.6.3-1.el7           zeroc-ice-el7          3.4 M\n php-ice-devel      x86_64   3.6.3-1.el7           zeroc-ice-el7           66 k\nUpdating for dependencies:\n glibc              x86_64   2.17-157.el7_3.1      updates                3.6 M\n glibc-common       x86_64   2.17-157.el7_3.1      updates                 11 M\n\nTransaction Summary\n================================================================================\nInstall  1 Package  (+8 Dependent packages)\nUpgrade             ( 2 Dependent packages)\n\nTotal download size: 27 M\nDownloading packages:\nDelta RPMs reduced 3.6 M of updates to 907 k (75% saved)\n"]}

...

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
omero-server-ice35         : ok=76   changed=54   unreachable=0    failed=0
omero-server-ice36         : ok=9    changed=7    unreachable=0    failed=1
```

**Comment by manics** [comment]
> `"https://zeroc.com/download/rpm/el7/x86_64/libice-java-3.6.3-1.el7.x86_64.rpm: [Errno 14] curl#18 - \"transfer closed with 915304 bytes remaining to read\"\nTrying other mirror.\n\n\nError downloading packages:\n  libice-java-3.6.3-1.el7.x86_64: [Errno 256] No more mirrors to try.\n\n"`

Looks like a zeroc repository problem

**Comment by joshmoore** [comment]
Ok. Looks like this week I'm getting a real error:

```
TASK [ansible-role-omero-server : omero | install omero] ***********************
fatal: [omero-server-ice35]: FAILED! => {"changed": false, "cmd": "/home/omero/omego/bin/omego install --release latest --sym OMERO.server --prestartfile /home/omero/config/omero-base.config --prestartfile /home/omero/config/omero-additional.config --ice 3.5 -qq --no-start --dbhost localhost --dbuser omero --dbname omero --dbpass omero --rootpass omero --initdb", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
fatal: [omero-server-ice36]: FAILED! => {"changed": false, "cmd": "/home/omero/omego/bin/omego install --release latest --sym OMERO.server --prestartfile /home/omero/config/omero-base.config --prestartfile /home/omero/config/omero-additional.config --ice 3.6 -qq --no-start --dbhost localhost --dbuser omero --dbname omero --dbpass omero --rootpass omero --initdb", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

RUNNING HANDLER [openmicroscopy.nginx : restart nginx] *************************

RUNNING HANDLER [openmicroscopy.postgresql : restart postgresql] ***************

PLAY RECAP *********************************************************************
omero-server-ice35         : ok=51   changed=38   unreachable=0    failed=1
omero-server-ice36         : ok=53   changed=40   unreachable=0    failed=1
```

i.e. how do we handle this venv bug?

**Comment by manics** [comment]
Is this still Ansible 2.2? If so see https://github.com/openmicroscopy/design/pull/73

**Comment by joshmoore** [comment]
Can you cherry-pick this as well then:

```
commit d8c244c3ecdea36da9eff192196f8c8ea2f840c8
Author: jmoore <josh@glencoesoftware.com>
Date:   Tue Feb 7 13:35:03 2017 +0100

    Fail molecule for ansible 2.2+
```

Been caught by that enough. Or if ansible >= 2.2 is detected, should the default omego be to `/usr/bin`?

**Comment by manics** [comment]
> Been caught by that enough. Or if ansible >= 2.2 is detected, should the default omego be to /usr/bin?

In that case why not make it the default regardless of version?

**Comment by joshmoore** [comment]
> In that case why not make it the default regardless of version?

I don't understand. Doesn't the value need to be set to where `omego` was actually placed?

**Comment by manics** [comment]
It's a bug in Ansible 2.2, the virtualenv is created but omego is installed somewhere else. I think it's better to use a fix that should work with both versions, especially since if the 2.2 bug is fixed in a later release it'll break again.

**Comment by joshmoore** [comment]
```
============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /opt/own-ansible/ansible-role-omero-server, inifile:
plugins: testinfra-1.4.5
collected 16 itemss

tests/test_default.py ................

============================ pytest-warning summary ============================
WP1 None Module already imported so can not be re-written: testinfra
================ 16 passed, 1 pytest-warnings in 44.17 seconds =================
--> Destroying instances...
==> omero-server-ice36: Forcing shutdown of VM...
==> omero-server-ice36: Destroying VM and associated drives...
==> omero-server-ice35: Forcing shutdown of VM...
==> omero-server-ice35: Destroying VM and associated drives...
```

_Whew._ Ok. First time it passed for me. From my side, it'd be nice to fix the 2.2 issue (since it was quite the time sync for me) but can also be later.

**Comment by joshmoore** [comment]
NB: perhaps an issue for https://github.com/openmicroscopy/design/pull/73, but there's not a clear variable prefix here unless this role should actually be named "omero".

**Comment by manics** [comment]
> From my side, it'd be nice to fix the 2.2 issue (since it was quite the time sync for me) but can also be later.

I can't see a clean way of fixing this without a breaking change, unless you want me to add fail if `ansible > 2.1`?

>  but there's not a clear variable prefix here unless this role should actually be named "omero".

That's because it was written before we had any standards. I'll can prefix everything but it'll obviously be a breaking change

**Comment by joshmoore** [comment]
> I can't see a clean way of fixing this without a breaking change, unless you want me to add fail if ansible > 2.1?

That's what cherry-picking d8c244c3ecdea36da9eff192196f8c8ea2f840c8 would do. Only alternative (and I didn't explore it) is to override the default if >= 2.2

> That's because it was written before we had any standards. I can prefix everything but it'll obviously be a breaking change

Yep, not saying it's specific to this PR, just pointing out that it's become obvious here.

**Comment by joshmoore** [comment]
Green. Merging and tagging as 1.2.0

**Pull request merged**
