### PR TITLE
Refactor omero-server role (breaking changes)

### PR DESCRIPTION
**Pull request by manics**
This implements https://github.com/openmicroscopy/design/pull/73 in conjunction with
- https://github.com/openmicroscopy/ansible-role-omero-common
- https://github.com/openmicroscopy/ansible-role-omego
- https://github.com/openmicroscopy/ansible-role-omero-web

It also implements a variant of https://github.com/openmicroscopy/design/issues/70 using a systemd `ExecStartPre` script to reinitialise the omero configuration from a directory of `*.omero` files.

Major changes from version `1.*` of this role are outlined in `CHANGES.md`.

### CODE REVIEW

**Comment by joshmoore** [comment]
The changes document reads quite well, but I haven't been able to review all of them individually (in terms of naming etc). To some degree, we almost need a period of low-version numbers (omero-server2:0.1.0) to work through the API here before saying that this is stable. Anyone have suggestions on how to manage that?

**Comment by manics** [comment]
@sbesson we need some advice on naming versions 😄

**Comment by sbesson** [comment]
@manics :) An alternative to https://github.com/openmicroscopy/ansible-role-omero-server/pull/8#issuecomment-290746153 might be to maintain the same role name but express the fact we are working towards an API-breaking `2.0.0` using explicit semver tags like `2.0.0-m1` or  `2.0.0-alpha1`. Are the latter supported by Ansible Galaxy as I could not find any doc on their versioning scheme? Also what happens if a Galaxy requirements file does not contain any version for a tagged role - does it default to the HEAD of `master`, the last role tag or does it fail?

**Comment by manics** [comment]
I don't know what the behaviour of tags is. If we're happy to test without tagged versions we could create a separate `develop` branch, and depend on the git-hash?

**Comment by manics** [comment]
Last four commits:
- Change the system user to `omero-server` (requested on an issue in a private repo)
- Add some travis/ansible/omego/omero workarounds.

**Comment by manics** [comment]
Last four commits:
- Change the system user to `omero-server` (requested on an issue in a private repo)
- Add some travis/ansible/omego/omero workarounds.

**Comment by manics** [comment]
Last commit uses https://pypi.python.org/pypi/ome-ansible-molecule-dependencies/ for bundling dependencies

**Comment by sbesson** [comment]
As discussed with @joshmoore and @manics, assuming there is no additional planned breaking change, I would vote for merging this into master, tag it `2.0.0-m1` (or maybe `2.0.0-rc1), test it in the various places and then release `2.0.0` post testing. If needed, we can derive a stable branch for `1.x.y` releases.

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
