### PR TITLE
Allow system user creation to be disabled

### PR DESCRIPTION
**Pull request by manics**
Fixes https://github.com/openmicroscopy/management_tools/issues/623#issuecomment-365995388

Tag: `2.0.4` or `2.1.0` depending on whether you see this as a feature or a bug-fix.

### CODE REVIEW

**Comment by joshmoore** [comment]
Seems low-enough impact. Happy to go for `2.0.4` if there are no objections.

A test for the `False` case would need to manually create a user? Do we want to consider prod-playbooks as valid tests for this repo?

cc: @sbesson @kennethgillen

**Comment by sbesson** [comment]
Happy to see this as a `2.0.4`. Is there some reference we can mention in the public role about the conditions where `omero_server_system_user_manage` should be set to `False`?

**Comment by manics** [comment]
The only report I'm aware of is https://github.com/openmicroscopy/management_tools/issues/623#issuecomment-365995388 so I'd consider it a corner case for now, since the README is already quite dense.

**Comment by manics** [comment]
I was tempted to put it under `# Expert users only!` until we had evidence of a wider issue but decided against.

**Comment by joshmoore** [comment]
Ok. Releasing as `2.0.4` then. I'm unsure what review process etc. is going to pick up the fact that this variable is not exactly what we want it to be. Issue or card seems like too much noise.

**Comment by kennethgillen** [comment]
I would say prod-playbook passing run to be a valid test, yes @joshmoore.

**Pull request merged**
