### PR TITLE
issue 21 fix - force get 

### LINKED ISSUE #21: Role may fail in dry-run mode
Reported by @pwalczysko:
`TASK [openmicroscopy.omero-server : omero server | get latest version] **********************************************************************************************************************************************`
`fatal: [ ]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'url'\n\nThe error appears to have been in 'ansible-examples-omero/public-user/roles/openmicroscopy.omero-server/tasks/omero-install.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# operations instead\n- name: omero server | get latest version\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'url'"}`
This is because https://github.com/openmicroscopy/ansible-role-omero-server/blob/2.0.1/tasks/omero-install.yml#L32 is not run in check-mode, leading to the undefined variable later.

### PR DESCRIPTION
**Pull request by kennethgillen**
Fixes #21 

Adding force run when --check specified by user.

### CODE REVIEW

**Comment by sbesson** [comment]
Sounds reasonable and should be good to merge and tag as `2.0.2` once Travis validates the changes from my perspective. @manics: you happy with the change?

**Comment by manics** [comment]
Looks fine. Presumably it's been tested with and without check-mode on a real server?

**Comment by kennethgillen** [comment]
Ran `with` check mode and it worked where it didn't before.

 Will get to `without` this morning.

**Comment by kennethgillen** [comment]
@sbesson  - ran successfully without `--check`

```
TASK [openmicroscopy.omero-server : omero server | get latest version] ********************************************************************************************************************************************
ok: [ome-demoserver.openmicroscopy.org]
```

**Comment by sbesson** [comment]
Thanks both, tagged and releases to https://galaxy.ansible.com/openmicroscopy/omero-server/.

**Pull request merged**
