### PR TITLE
Update postgres config for 3.0.0-m2

### PR DESCRIPTION
**Pull request by manics**
The postgresql role was tagged with a breaking change, so this role needs to be updated.

### CODE REVIEW

**Comment by joshmoore** [comment]
Would this have been detected with a cron job on this repo?

**Comment by manics** [comment]
yes

**Comment by sbesson** [comment]
From a practical point of view, I can confirm the failures without this PR and the success with it. The changes also match the upstream breaking changes in https://github.com/openmicroscopy/ansible-role-postgresql/pull/7.

 In terms of dependencies mapping, my understanding is the following:
- the last tag of this role `openmicroscopy.omero-server 2.0.0-m3` requires  `openmicroscopy.postgresql 3.0.0-m1` and earlier
- with this PR, the next tag `openmicroscopy.omero-server 2.0.0-m4?` will require `openmicroscopy.postgresql 3.0.0-m2` and above.

Is there a way to express this mapping  e.g. in `meta/main.yml` and enforce the minimal version requirement?

**Comment by manics** [comment]
I think you can include the version in `meta/main.yml` but IIRC we decided on a policy of only specifying versions in a requirements.yml file, not within roles.

**Comment by joshmoore** [comment]
I think @sbesson was waiting on a follow-up to https://github.com/ome/ansible-examples-omero/pull/3#discussion_r139134596

Can we outline the general testing for these 2 PRs together?

**Comment by manics** [comment]
What's the purpose of  ome/ansible-examples-omero? To provide a recommended production playbook? Or to track the latest tags of ansible roles?

**Comment by joshmoore** [comment]
The former, I'd say. I.e. some stable recommendation.

**Comment by manics** [comment]
Then this needs to be merged so the requirements in examples can be fixed

**Comment by joshmoore** [comment]
Except @sbesson has proposed that we also pin here, if I understand correctly.

**Comment by manics** [comment]
In that case should we pin all roles, not just postgres, and similarly for other roles?

**Comment by sbesson** [comment]
Coming back to this, while I think there is some value in expressing the version compatibility in the role eventually (maybe via some kind of CHANGELOG as a first step?), I certainly understand the impact of modifying the policy highlighted in https://github.com/openmicroscopy/ansible-role-omero-server/pull/17#issuecomment-329506190 notably in terms of reviewing all of the roles.

So :+1: for getting this in while making sure the requirements.yml in our public facing playbooks are up-to-date and pinned to the recommended stable.

**Comment by joshmoore** [comment]
Merging then.

**Pull request merged**
